name: 'dbt_segment_metrics'
version: '0.7.0'
require-dbt-version: [">=1.0.0", "<2.0.0"]
config-version: 2

profile: houseware_metrics

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  dbt_segment_metrics:
    +materialized: table

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:

  # put the database and schema where segment raw data is stored
  segment__source: HOUSEWARE_HOUSEWARE
  segment__schema: fivetran_segment
  # location of raw data table
  segment_page_views_table: "{{ source(var('segment__schema'), 'pages') }}"
  # number of trailing hours to re-sessionize for.
  # events can come in late and we want to still be able to incorporate
  # them into the definition of a session without needing a full refresh.
  segment_sessionization_trailing_window: 3
  # sessionization inactivity cutoff: of there is a gap in page view times
  # that exceeds this number of seconds, the subsequent page view will
  # start a new session.
  segment_inactivity_cutoff: 30 * 60
  segment_pass_through_columns: []
  segment_bigquery_partition_granularity: "day"
