
version: 2

jobs:
  build:
    docker:
      - image: cimg/python:3.9.9
      - image: circleci/postgres:9.6.5-alpine-ram

    steps:
      - checkout

      - run:
          run: setup_creds
          command: |
            echo $BIGQUERY_SERVICE_ACCOUNT_JSON > ${HOME}/bigquery-service-key.json

      - restore_cache:
          key: deps1-{{ .Branch }}

      - run:
          name: "Setup dbt"
          command: |
            python3 -m venv dbt_venv
            . dbt_venv/bin/activate

            pip install --upgrade pip setuptools
            pip install --pre dbt

            mkdir -p ~/.dbt
            cp integration_tests/ci/sample.profiles.yml ~/.dbt/profiles.yml

      - run:
          name: "Run Tests - Redshift"
          command: |
            . dbt_venv/bin/activate
            echo `pwd`
            cd integration_tests
            dbt deps
            dbt seed --target redshift
            dbt run --target redshift --full-refresh
            dbt run --target redshift

      - run:
          name: "Run Tests - Snowflake"
          command: |
            . dbt_venv/bin/activate
            echo `pwd`
            cd integration_tests
            dbt deps
            dbt seed --target snowflake
            dbt run --target snowflake --full-refresh
            dbt run --target snowflake

      - run:
          name: "Run Tests - BigQuery"
          environment:
              BIGQUERY_SERVICE_KEY_PATH: "/home/circleci/bigquery-service-key.json"

          command: |
            . dbt_venv/bin/activate
            echo `pwd`
            cd integration_tests
            dbt deps
            dbt seed --target bigquery
            dbt run --target bigquery --full-refresh
            dbt run --target bigquery

      - save_cache:
          key: deps1-{{ .Branch }}
          paths:
            - "dbt_venv"
