version: 2

sources:
 - name: segment
   schema: "{{ var('segment__schema', 'fivetran_segment') }}"
   database: "{{ var('segment__source', target.database) }}"
   tables: 
    - name: pages
    - name: identifies
    - name: tracks
    - name: users
